version: '3'

networks:
  default:
    driver: bridge

services:
  mariadb:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - default
    labels:
      - 'traefik.enable=false'
  phpfpm:
    image: ufhweb/php:7.2-wordpress
    depends_on:
      - mariadb
    volumes:
      - "./wordpress:/var/www/html"
      - "./data/debug:/data/debug"
      - "./Docker/logs/php:/var/log/php-fpm"
    restart: always
    networks:
      - default
    labels:
      - 'traefik.enable=false'
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
  httpd:
    depends_on:
      - phpfpm
    image: ufhweb/apache:2.4
    volumes:
      - "./wordpress:/var/www/html"
      - "./logs/httpd:/var/log/apache2"
    restart: always
    networks:
      - default
