version: '3'

services:
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025
  mariadb:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  redis:
    image: redis:latest
    restart: always
  phpfpm:
    image: chriswiegman/php:7.2
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./wordpress:/var/www/html"
      - "./data/debug:/data/debug"
    restart: always
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
  httpd:
    depends_on:
      - phpfpm
    image: chriswiegman/apache
    volumes:
      - "./wordpress:/var/www/html"
      - "./logs/httpd:/var/log/apache2"
    restart: always
