version: '3'

networks:
  ouroboros_default:
    external: true
  docker-wordpress:
    driver: bridge

services:
  mariadb:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    labels:
      - "traefik.enable=false"
    networks:
      - docker-wordpress
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025
    labels:
      - "traefik.enable=false"
    networks:
      - docker-wordpress
  redis:
    image: redis:latest
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - docker-wordpress
  phpfpm:
    image: chriswiegman/php:7.2
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./wordpress:/var/www/html"
      - "./data/debug:/data/debug"
    restart: always
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
    labels:
      - "traefik.enable=false"
    networks:
      - docker-wordpress
  httpd:
    depends_on:
      - phpfpm
    image: chriswiegman/apache
    volumes:
      - "./wordpress:/var/www/html"
      - "./logs/httpd:/var/log/apache2"
    restart: always
    networks:
      - ouroboros_default
      - docker-wordpress
    labels:
      - 'traefik.frontend.rule=Host:wordpress.our'
      - 'traefik.domain=wordpress.our'
