version: '3'

networks:
  default:
    driver: bridge
  ouroboros_default:
    external: true

services:
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    environment:
      MAILCATCHER_PORT: 1025
    networks:
      - default
    labels:
      - 'traefik.enable=false'
  mariadb:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - default
    labels:
      - 'traefik.enable=false'
  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    labels:
      - 'traefik.enable=false'
  phpfpm:
    image: chriswiegman/php:7.2
    depends_on:
      - mariadb
      - redis
    volumes:
      - "./wordpress:/var/www/html"
      - "./data/debug:/data/debug"
    restart: always
    networks:
      - default
    labels:
      - 'traefik.enable=false'
  httpd:
    depends_on:
      - phpfpm
    image: chriswiegman/apache
    volumes:
      - "./wordpress:/var/www/html"
      - "./logs/httpd:/var/log/apache2"
    restart: always
    networks:
      - default
      - ouroboros_default
    labels:
      - 'traefik.frontend.rule=Host:docker-wordpress.test'
      - 'traefik.domain=docker-wordpress.test'
      - 'traefik.enable=true'

