version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  phpfpm:
    image: chriswiegman/php:7.2
    depends_on:
      - mariadb
    volumes:
      - "./wordpress:/var/www/html"
      - "./data/debug:/data/debug"
    restart: always
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
  httpd:
    depends_on:
      - phpfpm
    image: chriswiegman/apache
    volumes:
      - "./wordpress:/var/www/html"
      - "./logs/httpd:/var/log/apache2"
    restart: always
    environment:
      - VIRTUAL_HOST=wordpress.local
